type = "directrequest"
schemaVersion = 1
name = ""
maxTaskDuration = "0s"
contractAddress = "0x8E5A56F915B56FCFdB8Cc7E881D68b0d72900014"
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type=cborparse data="$(decode_log.data)"]
    fetch        [type=bridge name="verifier" requestData="{\\"id\\": $(jobSpec.externalJobID), \\"data\\": { \\"jwt\\": $(decode_cbor.jwt) \\"email\\": $(decode_cbor.email), \\"proof\\": $(decode_cbor.proof), \\"publicAddress\\": $(decode_cbor.publicAddress)}}"]
    parse_proof    [type=jsonparse path="data,proof" data="$(fetch)"] 
    parse_email    [type=jsonparse path="data,email" data="$(fetch)"]
    parse_publicAddress [type=jsonparse path="data,publicAddress" data="$(fetch)"]
    encode_data  [type=ethabiencode abi="(string _email, bytes32 _proof, address _publicAddress)" data="{ \\"_email\\": $(parse_email), \\"_proof\\": $(parse_proof), \\"_publicAddress\\": $(parse_publicAddress) }"]
    encode_tx    [type=ethabiencode
                  abi="fulfillOracleRequest(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type=ethtx to="0x8E5A56F915B56FCFdB8Cc7E881D68b0d72900014" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse_proof -> parse_email -> parse_publicAddress -> encode_data -> encode_tx -> submit_tx
"""
